import Head from "next/head";
import Image from "next/image";
import Body from "~/components/layout/Body";

const AboutUs = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <div className="mx-auto flex  w-full max-w-6xl justify-between gap-x-11 py-28">
          <div className=" w-3/5 ">
            <div className="flex  flex-col">
              <h3 className="text-xl font-extrabold tracking-tight text-accent  ">
                About
              </h3>
              <h2 className="text-5xl font-extrabold tracking-tight text-primary sm:text-[5rem]">
                Meet Judy Sledge
              </h2>
            </div>

            <p className="my-5 py-5 text-lg font-medium  text-default">
              Lorem excepteur enim enim eu minim amet. Dolor consectetur
              proident occaecat id sunt ex ex eu. Amet esse ipsum irure eu
              mollit dolor sit quis. Sit cupidatat quis et anim mollit sint. Et
              veniam consectetur Lorem tempor tempor id reprehenderit irure
              adipisicing veniam irure eiusmod dolore.
            </p>
            <p className="my-5 py-5 text-lg font-medium  text-default">
              Lorem excepteur enim enim eu minim amet. Dolor consectetur
              proident occaecat id sunt ex ex eu. Amet esse ipsum irure eu
              mollit dolor sit quis. Sit cupidatat quis et anim mollit sint. Et
              veniam consectetur Lorem tempor tempor id reprehenderit irure
              adipisicing veniam irure eiusmod dolore.
            </p>
            <p className="my-5 py-5 text-lg font-medium  text-default">
              Lorem excepteur enim enim eu minim amet. Dolor consectetur
              proident occaecat id sunt ex ex eu. Amet esse ipsum irure eu
              mollit dolor sit quis. Sit cupidatat quis et anim mollit sint. Et
              veniam consectetur Lorem tempor tempor id reprehenderit irure
              adipisicing veniam irure eiusmod dolore.
            </p>
          </div>

          <div className=" relative aspect-square w-2/5 ">
            <Image
              layout="fill"
              src="/images/about_stock.png"
              alt="Judy Sledge"
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
        </div>
      </Body>
    </>
  );
};
export default AboutUs;
