import Head from "next/head";
import Image from "next/image";
import Body from "~/components/layout/Body";

export default function AboutUs() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <div className="mx-auto flex  w-full max-w-6xl justify-between gap-x-11 py-28">
          <div className="divide-y  divide-gray-700">
            <div className="space-y-2 pb-8 pt-6 md:space-y-5">
              <h1 className="md:leading-14 text-3xl font-extrabold leading-9 tracking-tight  text-primary sm:text-4xl sm:leading-10 md:text-6xl">
                Latest
              </h1>
              <p className="text-lg leading-7  text-primary/50">
                A blog created with Next.js and Tailwind.css
              </p>
            </div>
            <ul className="divide-y  divide-gray-700">
              <li className="py-12">
                <article>
                  <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                    <dl>
                      <dt className="sr-only">Published on</dt>
                      <dd className="text-base font-medium leading-6  text-primary/80">
                        <time dateTime="2021-08-07T15:32:14.000Z">
                          August 7, 2021
                        </time>
                      </dd>
                    </dl>
                    <div className="space-y-5 xl:col-span-3">
                      <div className="space-y-6">
                        <div>
                          <h2 className="text-2xl font-bold leading-8 tracking-tight">
                            <a
                              className=" text-primary/60"
                              href="/blog/new-features-in-v1"
                            >
                              New features in v1
                            </a>
                          </h2>
                          <div className="flex flex-wrap">
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/next-js"
                            >
                              next-js
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/tailwind"
                            >
                              tailwind
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/guide"
                            >
                              guide
                            </a>
                          </div>
                        </div>
                        <div className="prose max-w-none  text-primary/80">
                          An overview of the new features released in v1 - code
                          block copy, multiple authors, frontmatter layout and
                          more
                        </div>
                      </div>
                      <div className="text-base font-medium leading-6">
                        <a
                          className="text-accent hover:text-accent/80"
                          aria-label='Read "New features in v1"'
                          href="/blog/new-features-in-v1"
                        >
                          Read more →
                        </a>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
              <li className="py-12">
                <article>
                  <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                    <dl>
                      <dt className="sr-only">Published on</dt>
                      <dd className="text-base font-medium leading-6  text-primary/80">
                        <time dateTime="2021-05-02T00:00:00.000Z">
                          May 1, 2021
                        </time>
                      </dd>
                    </dl>
                    <div className="space-y-5 xl:col-span-3">
                      <div className="space-y-6">
                        <div>
                          <h2 className="text-2xl font-bold leading-8 tracking-tight">
                            <a
                              className=" text-primary/60"
                              href="/blog/nested-route/introducing-multi-part-posts-with-nested-routing"
                            >
                              Introducing Multi-part Posts with Nested Routing
                            </a>
                          </h2>
                          <div className="flex flex-wrap">
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/multi-author"
                            >
                              multi-author
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/next-js"
                            >
                              next-js
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/feature"
                            >
                              feature
                            </a>
                          </div>
                        </div>
                        <div className="prose max-w-none  text-primary/80">
                          The blog template supports posts in nested
                          sub-folders. This can be used to group posts of
                          similar content e.g. a multi-part course. This post is
                          itself an example of a nested route!
                        </div>
                      </div>
                      <div className="text-base font-medium leading-6">
                        <a
                          className="text-accent hover:text-accent/80"
                          aria-label='Read "Introducing Multi-part Posts with Nested Routing"'
                          href="/blog/nested-route/introducing-multi-part-posts-with-nested-routing"
                        >
                          Read more →
                        </a>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
              <li className="py-12">
                <article>
                  <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                    <dl>
                      <dt className="sr-only">Published on</dt>
                      <dd className="text-base font-medium leading-6  text-primary/80">
                        <time dateTime="2021-01-12T00:00:00.000Z">
                          January 11, 2021
                        </time>
                      </dd>
                    </dl>
                    <div className="space-y-5 xl:col-span-3">
                      <div className="space-y-6">
                        <div>
                          <h2 className="text-2xl font-bold leading-8 tracking-tight">
                            <a
                              className=" text-primary/60"
                              href="/blog/introducing-tailwind-nextjs-starter-blog"
                            >
                              Introducing Tailwind Nextjs Starter Blog
                            </a>
                          </h2>
                          <div className="flex flex-wrap">
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/next-js"
                            >
                              next-js
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/tailwind"
                            >
                              tailwind
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/guide"
                            >
                              guide
                            </a>
                          </div>
                        </div>
                        <div className="prose max-w-none  text-primary/80">
                          Looking for a performant, out of the box template,
                          with all the best in web technology to support your
                          blogging needs? Checkout the Tailwind Nextjs Starter
                          Blog template.
                        </div>
                      </div>
                      <div className="text-base font-medium leading-6">
                        <a
                          className="text-accent hover:text-accent/80"
                          aria-label='Read "Introducing Tailwind Nextjs Starter Blog"'
                          href="/blog/introducing-tailwind-nextjs-starter-blog"
                        >
                          Read more →
                        </a>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
              <li className="py-12">
                <article>
                  <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                    <dl>
                      <dt className="sr-only">Published on</dt>
                      <dd className="text-base font-medium leading-6  text-primary/80">
                        <time dateTime="2020-12-21T00:00:00.000Z">
                          December 20, 2020
                        </time>
                      </dd>
                    </dl>
                    <div className="space-y-5 xl:col-span-3">
                      <div className="space-y-6">
                        <div>
                          <h2 className="text-2xl font-bold leading-8 tracking-tight">
                            <a
                              className=" text-primary/60"
                              href="/blog/deriving-ols-estimator"
                            >
                              Deriving the OLS Estimator
                            </a>
                          </h2>
                          <div className="flex flex-wrap">
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/next-js"
                            >
                              next-js
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/math"
                            >
                              math
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/ols"
                            >
                              ols
                            </a>
                          </div>
                        </div>
                        <div className="prose max-w-none  text-primary/80">
                          How to derive the OLS Estimator with matrix notation
                          and a tour of math typesetting using markdown with the
                          help of KaTeX.
                        </div>
                      </div>
                      <div className="text-base font-medium leading-6">
                        <a
                          className="text-accent hover:text-accent/80"
                          aria-label='Read "Deriving the OLS Estimator"'
                          href="/blog/deriving-ols-estimator"
                        >
                          Read more →
                        </a>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
              <li className="py-12">
                <article>
                  <div className="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
                    <dl>
                      <dt className="sr-only">Published on</dt>
                      <dd className="text-base font-medium leading-6  text-primary/80">
                        <time dateTime="2020-11-11T00:00:00.000Z">
                          November 10, 2020
                        </time>
                      </dd>
                    </dl>
                    <div className="space-y-5 xl:col-span-3">
                      <div className="space-y-6">
                        <div>
                          <h2 className="text-2xl font-bold leading-8 tracking-tight">
                            <a
                              className=" text-primary/60"
                              href="/blog/guide-to-using-images-in-nextjs"
                            >
                              Images in Next.js
                            </a>
                          </h2>
                          <div className="flex flex-wrap">
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/next-js"
                            >
                              next-js
                            </a>
                            <a
                              className="mr-3 text-sm font-medium uppercase text-accent hover:text-accent/80"
                              href="/tags/guide"
                            >
                              guide
                            </a>
                          </div>
                        </div>
                        <div className="prose max-w-none  text-primary/80">
                          In this article we introduce adding images in the
                          tailwind starter blog and the benefits and limitations
                          of the next/image component.
                        </div>
                      </div>
                      <div className="text-base font-medium leading-6">
                        <a
                          className="text-accent hover:text-accent/80"
                          aria-label='Read "Images in Next.js"'
                          href="/blog/guide-to-using-images-in-nextjs"
                        >
                          Read more →
                        </a>
                      </div>
                    </div>
                  </div>
                </article>
              </li>
            </ul>
          </div>
        </div>
      </Body>
    </>
  );
}
