import Head from "next/head";

import Body from "~/components/layout/Body";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <div className="mx-auto flex  w-full max-w-6xl justify-between gap-x-11 ">
          <div className="flex  w-3/5 flex-col">
            <h3 className="text-xl font-extrabold tracking-tight text-accent  ">
              Questions, Comments, Concerns?
            </h3>
            <h2 className="text-5xl font-extrabold tracking-tight text-primary sm:text-[5rem]">
              Contact Us
            </h2>
            <p className=" mt-5 text-lg font-medium  text-default">
              Judy Sledge LLC.
            </p>{" "}
            <p className=" text-lg font-medium  text-default">
              1111 Random Address St.
            </p>{" "}
            <p className="text-lg font-medium  text-default">Detroit, MI</p>
            <p className="mt-5 text-lg font-medium  text-default">
              testEmail@test.com
            </p>
            <p className="mb-5 text-lg font-medium  text-default">
              999-999-9999
            </p>
          </div>
          <form className=" mx-auto flex w-4/5 flex-col space-y-4 rounded-lg bg-accent/5 p-12 shadow-xl">
            <h1 className="text-center text-lg font-semibold text-default">
              Get in touch
            </h1>
            <div className="space-y-2">
              <label className="text-default" htmlFor="frm-email">
                Email
              </label>
              <input
                className="w-full rounded bg-accent/20 p-2 text-black"
                id="frm-email"
                type="email"
                name="email"
                autoComplete="email"
                required
              />
            </div>
            <div className="space-y-2">
              <label className="text-default" htmlFor="frm-phone">
                Phone
              </label>
              <input
                className="w-full rounded bg-accent/20 p-2 text-black"
                id="frm-phone"
                type="text"
                name="phone"
                autoComplete="tel"
                required
              />
            </div>
            <div className="flex space-x-4">
              <div className="flex-1 space-y-2">
                <label className="text-default" htmlFor="frm-first">
                  First Name
                </label>
                <input
                  className="w-full rounded bg-accent/20 p-2 text-black"
                  id="frm-first"
                  type="text"
                  name="first"
                  autoComplete="given-name"
                  required
                />
              </div>
              <div className="flex-1 space-y-2">
                <label className="text-default" htmlFor="frm-last">
                  Last Name
                </label>
                <input
                  className="w-full rounded bg-accent/20 p-2 text-black"
                  id="frm-last"
                  type="text"
                  name="last"
                  autoComplete="family-name"
                  required
                />
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-default" htmlFor="frm-message">
                Message
              </label>
              <textarea
                className="h-24 w-full resize-none rounded bg-accent/20 p-2 text-black"
                id="frm-message"
                rows={6}
                name="message"
              ></textarea>
            </div>
            <div className="flex justify-center">
              <button className="rounded-full bg-accent/10 px-10 py-3 font-semibold text-default no-underline transition hover:bg-accent/20">
                Submit
              </button>
            </div>
          </form>
        </div>
      </Body>
    </>
  );
}
