import Head from "next/head";
import Image from "next/image";
import Body from "~/components/layout/Body";

export default function Gallery() {
  return (
    <>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <div className="mx-auto flex  w-full max-w-6xl justify-between gap-x-5 pt-16">
          <div className="space-y-2 pb-8 pt-6 md:space-y-5">
            <h1 className="md:leading-14 text-3xl font-extrabold leading-9 tracking-tight  text-primary sm:text-4xl sm:leading-10 md:text-6xl">
              Gallery
            </h1>{" "}
            <p className="text-lg leading-7  text-primary/50">
              A blog created with Next.js and Tailwind.css
            </p>
          </div>
        </div>

        <div className="mx-auto grid w-full max-w-6xl  grid-cols-1 justify-between gap-x-5 gap-y-5  py-16 md:grid-cols-3 lg:grid-cols-4">
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_1.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_2.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_7.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/hero.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_3.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>{" "}
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_4.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_5.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/art_stock.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/dress_stock.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_9.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/about_stock.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
          <div className=" relative col-span-1 aspect-square">
            <Image
              layout="fill"
              src="/images/stock_8.png"
              alt="gallery "
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
        </div>
      </Body>
    </>
  );
}
