import Head from "next/head";
import Image from "next/image";
import type { FC } from "react";

import type Stripe from "stripe";
import Featured from "~/components/Homepage/Featured";
import Hero from "~/components/Homepage/Hero";

import Body from "~/components/layout/Body";
import { stripe } from "~/server/stripe/client";

// Server side props
export async function getServerSideProps() {
  const res = await stripe.products.list({
    expand: ["data.default_price"],
  });
  const prices: Stripe.Product[] = res.data;
  console.log(prices);
  const products = prices.filter(
    (price: Stripe.Product) =>
      (price?.default_price as Stripe.Price).type === "one_time" && price.active
  );
  return {
    props: {
      prices: products.slice(0, 4),
    },
  };
}

interface IProps {
  prices: Stripe.Price[];
}

const Home: FC<IProps> = ({ prices }) => {
  return (
    <>
      <Head>
        <title>Judy Sledge</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Hero />
        <div className="mx-auto flex w-full  justify-between gap-x-11 bg-primary/5 pb-48 pt-24">
          <div className=" mx-auto flex h-96 w-full max-w-6xl flex-col justify-center">
            <h2 className=" text-6xl font-bold text-primary">
              A Style For Every Occasion,{" "}
              <span className="text-accent">Express</span> Yourself.
            </h2>
            <h3 className="my-3 py-5 text-2xl font-normal text-default">
              Lorem excepteur enim enim eu minim amet. Dolor consectetur
              proident occaecat id sunt ex ex eu. Amet esse ipsum irure eu
              mollit dolor sit quis. Sit cupidatat quis et anim mollit sint.
              Anim duis dolore irure veniam culpa consequat cillum fugiat.
              Proident mollit dolor adipisicing nostrud dolore ullamco aliqua
              dolore.
            </h3>
            <button className="w-fit  border-b-2 border-transparent text-left text-2xl font-bold text-accent/75 transition ease-linear hover:border-b-accent">
              Check Out The Collections →
            </button>
          </div>
        </div>
        <Featured items={prices} />
        <div className="mx-auto flex w-full max-w-6xl flex-col justify-between gap-x-11 py-28">
          <div className="mb-10 flex flex-row items-center">
            <div className="flex w-2/5 flex-col">
              <h3 className="text-xl font-extrabold tracking-tight text-accent  ">
                About
              </h3>
              <h2 className="text-5xl font-extrabold tracking-tight text-primary sm:text-[5rem]">
                Nice to Meet You
              </h2>
            </div>
            <div className="w-3/5">
              <p className="py-5 text-lg text-primary">
                Lorem excepteur enim enim eu minim amet. Dolor consectetur
                proident occaecat id sunt ex ex eu. Amet esse ipsum irure eu
                mollit dolor sit quis. Sit cupidatat quis et anim mollit sint.
                Et veniam consectetur Lorem tempor tempor id reprehenderit irure
                adipisicing veniam irure eiusmod dolore.
              </p>
            </div>{" "}
          </div>
          <div className=" relative aspect-video w-full">
            <Image
              layout="fill"
              src="/images/about_stock.png"
              alt="hero"
              objectFit="cover"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>
        </div>{" "}
        <div className="mx-auto flex w-full max-w-6xl flex-row items-center  justify-between  gap-12 px-4 pb-16">
          <div className=" relative aspect-video w-2/6">
            <Image
              layout="fill"
              src="/sledge_logo.png"
              alt="hero"
              objectFit="contain"
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              className="rounded"
            />
          </div>{" "}
          <div className="w-4/6">
            <p>
              Duis duis do nulla sunt dolore non aute esse pariatur commodo id.
              Amet duis aute cillum id eiusmod reprehenderit. Sunt voluptate
              proident cillum voluptate nisi sunt velit veniam mollit. In
              officia eiusmod laborum ea labore aute deserunt aliqua commodo
              deserunt laboris aliqua. Nostrud qui voluptate velit labore
              nostrud est esse Lorem velit magna. Sint nulla consequat enim
              excepteur excepteur aliquip culpa sit tempor fugiat aute
              cupidatat.
            </p>
          </div>
        </div>
      </Body>
    </>
  );
};
export default Home;
