import Head from "next/head";

import Body from "~/components/layout/Body";

const SuccessPage = () => {
  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <div className="mx-auto flex  w-full max-w-6xl justify-between gap-x-11 py-28">
          <div className=" w-3/5 ">
            <div className="flex  flex-col">
              <h3 className="text-xl font-extrabold tracking-tight text-accent  ">
                Your payment was successful. Thank you for your purchase.
              </h3>
            </div>
          </div>
        </div>
      </Body>
    </>
  );
};
export default SuccessPage;
