import Head from "next/head";
import type { FC } from "react";
import type Stripe from "stripe";
import ProductCard from "~/components/cards/ProductCard";
import Body from "~/components/layout/Body";
import { stripe } from "~/server/stripe/client";

export async function getStaticProps() {
  const res = await stripe.prices.list({
    expand: ["data.product"],
  });
  const prices: Stripe.Price[] = res.data;

  const products = prices.filter(
    (price: Stripe.Price) => price.type === "one_time"
  );
  return {
    props: {
      prices: products.slice(0, 4),
    },
  };
}

interface IProps {
  prices: Stripe.Price[];
}

const Products: FC<IProps> = ({ prices }) => {
  return (
    <>
      <Head>
        <title>Judy Sledge</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Body>
        <div className="mx-auto  mt-8 flex  w-full max-w-6xl flex-col justify-between gap-x-11">
          <div className="mb-16  flex flex-col">
            <h3 className="text-xl font-extrabold tracking-tight text-accent  ">
              All
            </h3>
            <h2 className="text-default1 text-5xl font-extrabold tracking-tight sm:text-[5rem]">
              Products
            </h2>
          </div>

          <div className="my-5 flex items-stretch gap-x-11">
            {prices &&
              prices.map((price: Stripe.Price, idx: number) => {
                const product = price.product as Stripe.Product;
                return (
                  <div className=" w-1/4 " key={idx}>
                    <ProductCard
                      title={product.name}
                      price={(price?.unit_amount as number) / 100}
                      image={product.images[0] as string}
                      category={product.metadata.category as string}
                    />
                  </div>
                );
              })}
            {/* <div className="w-1/4">
            <ProductCard
              title="Lorem Ipsum"
              price={34}
              image="/images/stock_1.png"
              category="Dress"
            />
          </div>{" "}
          <div className="w-1/4">
            <ProductCard
              title="Lorem Ipsum"
              price={34}
              image="/images/stock_2.png"
              category="Dress"
            />
          </div>
          <div className="w-1/4">
            <ProductCard
              title="Lorem Ipsum"
              price={34}
              image="/images/stock_6.png"
              category="Home Decor"
            />
          </div>
          <div className="w-1/4">
            <ProductCard
              title="Lorem Ipsum"
              price={34}
              image="/images/stock_8.png"
              category="Painting"
            />
          </div> */}
          </div>
        </div>
      </Body>
    </>
  );
};

export default Products;
